spring.application.name=roster-service
logging.level.org.springframework=INFO
server.port=0
spring.data.mongodb.uri=mongodb://localhost:27017/rosterdb
spring.data.mongodb.database=rosterdb
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

tokenSecret=wtjqd7tt672z4tn7gnf76igx2fyg2gfy7gnyg4wyfn73ytgy5nfywyvyrgvygby7fgnuyvzvycvynxcyrgncygnygyynguy4rgygyurgcywvyvygyg4wygfyg47g2uyzmIUNWIdhmx4ubgy4gnygnxygygygn
#spring.cloud.zookeeper.connect-string=localhost:2181
#spring.cloud.zookeeper.discovery.enabled=true
#spring.cloud.zookeeper.discovery.register=true
#spring.cloud.zookeeper.discovery.root=/services
eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# JMS  Settings

spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

jms.concurrency.min=5
jms.concurrency.max=10
jms.receive.timeout=5000

spring.activemq.prefetchPolicy.all=1000

spring.activemq.broker.persistent=true
spring.activemq.broker.dataDirectory=/opt/activemq/data

spring.activemq.broker.systemUsage.memoryUsage=512 mb
spring.activemq.broker.systemUsage.storeUsage=10 gb
spring.activemq.broker.systemUsage.tempUsage=5 gb

event.buffer.size=100
event.buffer.max-age-ms=5000

spring.activemq.pool.enabled=true
spring.activemq.pool.max-connections=50
spring.activemq.pool.idle-timeout=30000

spring.jms.listener.auto-startup=true
spring.jms.listener.concurrency=10
spring.jms.listener.max-concurrency=10
spring.jms.listener.receive-timeout=5000
# spring.jms.listener.acknowledge-mode=transacted

spring.jms.template.default-destination=roster.queue
spring.jms.template.delivery-mode=persistent