spring.application.name=discovery-service
server.port=8010
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
eureka.client.serviceUrl.defaultZone=http://localhost:8010/eureka
spring.security.user.name=PeoTv
spring.security.user.password=PeoVision